server:
  port: 7700
  ssl:
    enabled: true
    key-alias: localhost
    key-store: classpath:keystores/springboot.jks
    key-store-type: jks
    key-store-password: jabuka123
    key-password: jabuka123
    client-auth: none
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authModules
          uri: http://localhost:7702/
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: bankModules
          uri: http://localhost:7703/
          predicates:
            - Path=/bank-service/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: paypalModules
          uri: http://localhost:7706/
          predicates:
            - Path=/paypal/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: cryptoModules
          uri: http://localhost:7707/
          predicates:
            - Path=/crypto/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
